### ISSUE TITLE
Can't list keys ?

### ISSUE THREAD

**Issue by braksator** [ahs502/key-file-storage#3]
```
        var keyFileStorage = require("key-file-storage");
        var kfs = keyFileStorage("test/kfs/", 100);
        kfs['foo'] = 'x';
        kfs['bar'] = 'y';
        var keys = kfs["test/kfs/"];
        console.log(keys);
```
Output is [] whereas I expected something like ['foo', 'bar'].
I see the directory 'kfs' is created, and two files foo and bar exist containing "x" and "y".

**Comment by braksator** [comment]
Same result with the async version 
```
        kfs('test/kfs/').then(function(keys) {
            console.log(keys);
        });
```

**Comment by braksator** [comment]
Workaround

```
        var fs = require('fs');

        var files = fs.readdirSync("test/kfs/");
        console.log(files);
        // => [ 'bar', 'foo' ]
```

**Comment by ahs502** [comment]
I'm so sorry I'm answering you after several days!
I hope this will still be useful for you.

**Comment by ahs502** [comment]
The `"test/kfs/"` is your **base storage path** and acts like your **database name**.
Usually at initializing the `kfs` is the _only_ place for you to mention it in your code.
You should state your **collection name** to `kfs` to list your keys, which in your case would be `"/"` because the keys `'foo'` and `'bar'` are both in `"/"` within your database.

This will work fine:
```
var keyFileStorage = require("key-file-storage");
var kfs = keyFileStorage("test/kfs/", 100);
kfs['foo'] = 'x';
kfs['bar'] = 'y';
var keys = kfs["/"];
console.log(keys); //=> ['foo', 'bar']
```

**Comment by ahs502** [comment]
I would be happy to know if it solves the issue?!

**Comment by braksator** [comment]
Yes that works.  Cheers.

**Comment by ahs502** [comment]
:-)
